server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_qrtz?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Gepoint
  quartz:
    job-store-type: jdbc
    wait-for-jobs-to-complete-on-shutdown: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
schedule:
  cron:
    withJob1: "* 5 * * * ?"
    withJob2: "* 10 * * * ?"
logging:
  level:
    root: info